# Generated by Django 4.2.3 on 2023-08-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_instructor', '0003_instructorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='availability',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
